### ISSUE TITLE
Looks good!

### ISSUE THREAD

**Issue by mrpmorris** [two-thirty-seven/BlazorHtmxDemo#3]
I've just found this. It looks good, well done!

I'm wondering if there might be a way to automate some of this using Moxy.

Do you think it'd be a feasible approach to developing full web apps?

**Comment by two-thirty-seven** [comment]
It's possible but I'd have to take ideas on how Moxy could be used since I've not used it before.

**Comment by mrpmorris** [comment]
The moxy part was my intention.

Please disregard that part when considering the question :)
